spring:
  redis:
    host: 127.0.0.1
  application:
     name: audit_v2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 9085
    
server:
  port: 9085
  max-http-header-size: 200000

shuaicj.security.jwt.secret: 4fc2beb0d2ce11ea87d00242ac130003
redis:
  host: localhost
  port: 6379
