spring:
  application:
     name: dynamicsquerys


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 9091
    
server:
  port: 9091
